language: python
python:
- '3.4'
- '3.5'
- '3.6'
- '3.7'
install:
- pip install -r requirements.txt
script:
- nosetests
deploy:
  provider: pypi
  user: v1sion
  password: $PYPI_PASSWORD
  skip_existing: true
  on:
    branch: master
