language: python
python:
- '3.4'
- '3.5'
- '3.6'
- '3.7'
install:
- pip install -r requirements.txt
script:
- nosetests
deploy:
  provider: pypi
  user: v1sion
  password:
    secure: F8wgqk2HYhiIoea/eS3IVVNSGebnz8VEvywFW8NJ3iCCb9rlaib1RjSfo8lmLR1crzRhzJEHpyHJle6BxjORrIFIGZY+cO1+NBVj0arcxCKqEoLobTigfsAD3IP9NGE5Qco6/E4iXOXHJ9Dykv8PknrBc1DWqzlmH7er3Zy2rCRfcI34fG8bmnEwJeaT5Hpnc5nL+H7rKIBCMdDdLtqhQZdTLnidGZi/KGPoMxkTyAmZWIttOFlb2ownORIUn0RRFvOhwuaui13DuWtYmiyjWsiio5YuDIDOxlx19FVUS8ZiGi1yf1KEHHEhoASiLDouwcZhCclScQF03yxNLQMCrhrl89IzP/neqRu3c/TiYkarkAklplQN5/VFFb/+kLRJL61FUr1nG3jzm8lt+Sut8Mo8L68dqkvEip7hNvu850wCJpowY73rwOakbcsJgrr1qdVNyW13rBElDFXxUztLmE716aKso2a5m2fGTSH4d5fTAIQifkQPoRFVw4IFunUdOeVtDQVhGeYCtnVmi2kGkEbPE9Pmyb08SwubVn13i6Ln86/7dQcaZ0QrF19kcrhxGpuV7yz5Jqfveyjp54q58r/3f5c4SsM9rQM/HKMYZqt6HZyyAANjBTkEgIeuMyk0NqB1eb3cNRF89kTTAjpatwt7DNXzL0Ykm+dL58m6Ehk=
  skip_existing: true
  on:
    branch: master
